USE spice_test;
DROP TABLE IF EXISTS `spice_tag`;
DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `batch`;
DROP TABLE IF EXISTS `store`;
DROP TABLE IF EXISTS `spice`;
DROP TABLE IF EXISTS `brand`;
DROP TABLE IF EXISTS `user`;
